version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports: 
    - "5430:5432"
    environment:
    - POSTGRES_PASSWORD=Tornado
    - POSTGRES_USER=postgres
    - POSTGRES_DB=nestjs-base  
    image: postgres:14.3-alpine
    restart: always

